name = "assert"
version = "2.0.0"
license = "BSD"
author = ["Damian Rouson", "Dan Bonachea"]
maintainer = "rouson@lbl.gov"
copyright = "2024-2025 The Regents of the University of California, through Lawrence Berkeley National Laboratory"

[install]
library = true

