name: Build with gfortran

on: [push, pull_request]


jobs:
  gfortran-build:
    name: gfortran-${{ matrix.gcc_version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-22.04, ubuntu-24.04]
        gcc_version: [ 12, 13, 14 ]
        exclude:
          - os: ubuntu-22.04
            gcc_version: 13 # no package available
          - os: ubuntu-22.04
            gcc_version: 14 # no package available

    env:
      GCC_V: ${{ matrix.gcc_version }}
      FPM_FC: gfortran-${{ matrix.gcc_version }}
      EXTRA_FLAGS: -ffree-line-length-0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: fortran-lang/setup-fpm@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies Ubuntu
      if: contains(matrix.os, 'ubuntu') && 0
      run: |
        sudo apt-get update
        sudo apt list -a 'gfortran-*'
        sudo apt install -y gfortran-${GCC_V} build-essential
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}

    - name: Version info
      run: |
        set -x
        echo == TOOL VERSIONS ==
        uname -a
        if test -r /etc/os-release ; then cat /etc/os-release ; fi
        ${FPM_FC} --version
        fpm --version

    - name: Build and Test (Assertions OFF)
      env: 
        FPM_FLAGS:  --profile release --flag ${{ env.EXTRA_FLAGS }}
      run: |
        set -x
        fpm test --verbose ${FPM_FLAGS}
        fpm run --verbose --example false-assertion ${FPM_FLAGS}
        fpm run --verbose --example invoke-via-macro ${FPM_FLAGS}

    - name: Build and Test (Assertions ON)
      env: 
        FPM_FLAGS:  --profile release --flag ${{ env.EXTRA_FLAGS }} --flag -DASSERTIONS
      run: |
        set -x
        fpm test --verbose ${FPM_FLAGS}
        ( set +e ; fpm run --verbose --example false-assertion ${FPM_FLAGS} ; test $? = 1 )
        ( set +e ; fpm run --verbose --example invoke-via-macro ${FPM_FLAGS} ; test $? = 1 )


