name: Build with gfortran12

on: [push, pull_request]


jobs:
  gfortran12-build:
    runs-on: [ubuntu-22.04]

    env:
      GCC_V: 12
      FPM_FC: gfortran-12
      EXTRA_FLAGS: -ffree-line-length-0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: fortran-lang/setup-fpm@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt install -y gfortran-${GCC_V} build-essential
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}

    - name: Version info
      run: |
        set -x
        echo == TOOL VERSIONS ==
        uname -a
        cat /etc/os-release
        ${FPM_FC} --version
        fpm --version

    - name: Build and Test (Assertions OFF)
      env: 
        FC_FLAGS: ${EXTRA_FLAGS}
      run: |
        set -x
        fpm test --verbose --profile release --flag "${FC_FLAGS}"

    - name: Build and Test (Assertions ON)
      env: 
        FC_FLAGS: ${EXTRA_FLAGS} -DASSERTIONS
      run: |
        set -x
        fpm test --verbose --profile release --flag "${FC_FLAGS}"

